### ISSUE TITLE
Tooltip update after right click an item.

### ISSUE THREAD

**Issue by sipertruk** [shirsig/Postal#13] opened 2017-03-21 21:52 UTC
After right click an item the attachment is put in inventory, it is deleted and the next one moves under the cursor, but the tooltip is not updated until we move out and back.
Suggestion : update immediately the tooltip with the next item information.

**Comment by shirsig** [comment] 2017-03-22 04:34
I can't reproduce this. When I remove an attachment no other item moves in its place, and the tooltip is updated, to "Drag an item here to include it with your mail"

**Comment by sipertruk** [comment] 2017-03-22 13:50
"Item" was a poor choice of word from my part.
Here's a gif to dissipate all confusion.
![test](https://cloud.githubusercontent.com/assets/7644041/24200813/8b8d0202-0f0e-11e7-86f2-169090b3aec6.gif)

**Comment by shirsig** [comment] 2017-03-23 02:31
Ah I thought you were talking about the send mail tab. Should be fixed now, thanks.

**Closed by shirsig** 2017-03-23 02:31 UTC
